services:
  # 1. Node.js Backend Service
  backend_app:
    build: 
      context: ./backend
      # Assuming the Dockerfile is inside the 'backend' folder
      dockerfile: Dockerfile
    container_name: medpho_backend
    env_file: .env
    # Maps the container's internal port 8000 to the host port defined in your .env (e.g., PORT=8000)
    ports:
      - "${PORT}:8000" 
    # The application connects directly to the external DB using variables from .env
    restart: unless-stopped 
    networks:
      - medpho_net

  # 2. Metabase Service (connecting to external DB)
  metabase:
    image: metabase/metabase:latest
    container_name: medpho_metabase
    env_file: .env
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${METABASE_DB}
      # IMPORTANT: These variables must now point to your existing, external database's address and port
      MB_DB_HOST: ${POSTGRES_HOST} 
      MB_DB_PORT: ${POSTGRES_PORT} 
      MB_DB_USER: ${METABASE_USER}
      MB_DB_PASS: ${METABASE_PASS}
    # Maps the Metabase port to the host port defined in your .env (e.g., METABASE_PORT=3000)
    ports:
      - "${METABASE_PORT}:3000"
    volumes:
      - metabase_data:/metabase-data # Volume for Metabase configuration persistence
    restart: unless-stopped
    networks:
      - medpho_net
      
# Only volume required is for Metabase persistence
volumes:
  metabase_data:

networks:
  medpho_net:
    driver: bridge