version: "3.8"
services:
  db:
    image: postgres:14
    container_name: medpho_db
    env_file: .env
    environment:
      PGDATA: ${PGDATA}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d:ro   # initial SQL scripts (runs on first init)
      - ./import:/import:ro                         # optional: place CSVs here to import
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - medpho_net

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: medpho_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@medpho.local
      PGADMIN_DEFAULT_PASSWORD: AdminPass123!
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - medpho_net
    

  metabase:
    image: metabase/metabase:latest
    container_name: medpho_metabase
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${METABASE_DB}
      MB_DB_HOST: db
      MB_DB_PORT: 5432
      MB_DB_USER: ${METABASE_USER}
      MB_DB_PASS: ${METABASE_PASS}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${METABASE_PORT}:3000"
    volumes:
      - metabase_data:/metabase-data
    restart: unless-stopped
    networks:
      - medpho_net
  
      

volumes:
  postgres_data:
  metabase_data:
  pgadmin_data:

networks:
  medpho_net:
    driver: bridge
